"""Added can exchange property

Revision ID: 0a5c5d52f923
Revises: 27d946f17be6
Create Date: 2025-04-14 16:57:07.062749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a5c5d52f923'
down_revision: Union[str, None] = '27d946f17be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('can_exchange', sa.Boolean(), nullable=True))
    op.alter_column('user_currencies', 'balance',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text("'100'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_currencies', 'balance',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True,
               existing_server_default=sa.text("'100'"))
    op.drop_column('currencies', 'can_exchange')
    # ### end Alembic commands ###
