"""empty message

Revision ID: 1075b7c4ab97
Revises: 769a4e6499ac
Create Date: 2025-04-29 19:39:31.192309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1075b7c4ab97'
down_revision: Union[str, None] = '769a4e6499ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cooldowns', sa.Column('cooldown_type', sa.String(length=25), nullable=True))
    op.drop_column('cooldowns', 'display_name')
    op.alter_column('user_currencies', 'balance',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text("'100'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_currencies', 'balance',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True,
               existing_server_default=sa.text("'100'"))
    op.add_column('cooldowns', sa.Column('display_name', mysql.VARCHAR(length=25), nullable=True))
    op.drop_column('cooldowns', 'cooldown_type')
    # ### end Alembic commands ###
