"""Added jobs

Revision ID: 119ab9be4db6
Revises: 0a5c5d52f923
Create Date: 2025-04-15 17:15:08.905839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '119ab9be4db6'
down_revision: Union[str, None] = '0a5c5d52f923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=25), nullable=False),
    sa.Column('display_name', sa.String(length=25), nullable=True),
    sa.Column('min_pay', sa.Float(), nullable=True),
    sa.Column('max_pay', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.alter_column('user_currencies', 'balance',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text("'100'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_currencies', 'balance',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True,
               existing_server_default=sa.text("'100'"))
    op.drop_table('jobs')
    # ### end Alembic commands ###
