"""empty message

Revision ID: 5c5979cbe33d
Revises: 9203ca5e1801
Create Date: 2025-04-30 23:30:22.791303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c5979cbe33d'
down_revision: Union[str, None] = '9203ca5e1801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'jobs', 'currencies', ['currency_override'], ['currency_id'])
    op.alter_column('user_currencies', 'balance',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text("'100'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_currencies', 'balance',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True,
               existing_server_default=sa.text("'100'"))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    # ### end Alembic commands ###
