"""empty message

Revision ID: 769a4e6499ac
Revises: 5d885678f904
Create Date: 2025-04-29 17:59:36.581560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '769a4e6499ac'
down_revision: Union[str, None] = '5d885678f904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooldowns',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('expiry_timestamp', sa.DateTime(), nullable=True),
    sa.Column('display_name', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.alter_column('user_currencies', 'balance',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text("'100'"))
    op.drop_column('user_jobs', 'last_worked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_jobs', sa.Column('last_worked', mysql.DATETIME(), nullable=True))
    op.alter_column('user_currencies', 'balance',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True,
               existing_server_default=sa.text("'100'"))
    op.drop_table('cooldowns')
    # ### end Alembic commands ###
