"""UserJob different table

Revision ID: e50c9daad04f
Revises: 68c7f93db6f6
Create Date: 2025-04-15 17:36:33.545480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e50c9daad04f'
down_revision: Union[str, None] = '68c7f93db6f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_jobs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'job_id')
    )
    op.alter_column('user_currencies', 'balance',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text("'100'"))
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_id', mysql.VARCHAR(length=25), nullable=True))
    op.create_foreign_key('users_ibfk_1', 'users', 'jobs', ['job_id'], ['job_id'])
    op.alter_column('user_currencies', 'balance',
               existing_type=sa.Float(precision=53),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True,
               existing_server_default=sa.text("'100'"))
    op.drop_table('user_jobs')
    # ### end Alembic commands ###
